In [5]:
import pandas as pd
from sqlalchemy import create_engine, types

engine = create_engine('mysql://root:root@localhost/TrailDB')

df = pd.read_csv("car_crashes.csv",sep=',',quotechar='\'',encoding='utf8') 
df.to_sql('Car_crash',con=engine,index=False,if_exists='append')

ModuleNotFoundError: No module named 'MySQLdb'

In [2]:
import pandas as pd
from sqlalchemy import create_engine, types

engine = create_engine('mysql://root:root@localhost/TrailDB')

df = pd.read_csv("car_crashes.csv",sep=',',quotechar='\'',encoding='utf8') 
df.to_sql('Car_crash',con=engine,index=False,if_exists='append')

ModuleNotFoundError: No module named 'MySQLdb'

In [21]:
import pandas as pd
from sqlalchemy import create_engine, types

engine = create_engine('mysql+pymysql://root:root@127.0.0.1:3306/TrailDB?unix_socket=/var/run/mysqld/mysqld.sock')

df = pd.read_csv("car_crashes.csv",sep=',',quotechar='\'',encoding='utf8') 
df.to_sql('Car_crash',con=engine,index=False,if_exists='append')

OperationalError: (pymysql.err.OperationalError) (1045, "Access denied for user 'root'@'localhost' (using password: YES)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)

In [29]:
import pandas as pd
from sqlalchemy import create_engine, types

engine = create_engine('mysql+pymysql://root:@localhost/TrailDB?unix_socket=/var/run/mysqld/mysqld.sock')

df = pd.read_csv("car_crashes.csv",sep=',',quotechar='\'',encoding='utf8') 
df.to_sql('Car_crash',con=engine,index=False,if_exists='append')

In [30]:
df

,total,speeding,alcohol,not_distracted,no_previous,ins_premium,ins_losses,abbrev
0,18.8,7.332,5.640,18.048,15.040,784.55,145.08,AL
1,18.1,7.421,4.525,16.290,17.014,1053.48,133.93,AK
2,18.6,6.510,5.208,15.624,17.856,899.47,110.35,AZ
3,22.4,4.032,5.824,21.056,21.280,827.34,142.39,AR
4,12.0,4.200,3.360,10.920,10.680,878.41,165.63,CA
5,13.6,5.032,3.808,10.744,12.920,835.50,139.91,CO
6,10.8,4.968,3.888,9.396,8.856,1068.73,167.02,CT
7,16.2,6.156,4.860,14.094,16.038,1137.87,151.48,DE
8,5.9,2.006,1.593,5.900,5.900,1273.89,136.05,DC
9,17.9,3.759,5.191,16.468,16.826,1160.13,144.18,FL
10,15.6,2.964,3.900,14.820,14.508,913.15,142.80,GA
11,17.5,9.450,7.175,14.350,15.225,861.18,120.92,HI
12,15.3,5.508,4.437,13.005,14.994,641.96,82.75,ID
13,12.8,4.608,4.352,12.032,12.288,803.11,139.15,IL
14,14.5,3.625,4.205,13.775,13.775,710.46,108.92,IN
15,15.7,2.669,3.925,15.229,13.659,649.06,114.47,IA
16,17.8,4.806,4.272,13.706,15.130,780.45,133.80,KS
17,21.4,4.066,4.922,16.692,16.264,872.51,137.13,KY
18,20.5,7.175,6.765,14.965,20.090,1281.55,194.78,LA
19,15.1,5.738,4.530,13.137,12.684,661.88,96.57,ME
20,12.5,4.250,4.000,8.875,12.375,1048.78,192.70,MD
21,8.2,1.886,2.870,7.134,6.560,1011.14,135.63,MA
22,14.1,3.384,3.948,13.395,10.857,1110.61,152.26,MI
23,9.6,2.208,2.784,8.448,8.448,777.18,133.35,MN
24,17.6,2.640,5.456,1.760,17.600,896.07,155.77,MS
25,16.1,6.923,5.474,14.812,13.524,790.32,144.45,MO
26,21.4,8.346,9.416,17.976,18.190,816.21,85.15,MT
27,14.9,1.937,5.215,13.857,13.410,732.28,114.82,NE
28,14.7,5.439,4.704,13.965,14.553,1029.87,138.71,NV
29,11.6,4.060,3.480,10.092,9.628,746.54,120.21,NH
30,11.2,1.792,3.136,9.632,8.736,1301.52,159.85,NJ
31,18.4,3.496,4.968,12.328,18.032,869.85,120.75,NM
32,12.3,3.936,3.567,10.824,9.840,1234.31,150.01,NY
33,16.8,6.552,5.208,15.792,13.608,708.24,127.82,NC
34,23.9,5.497,10.038,23.661,20.554,688.75,109.72,ND
35,14.1,3.948,4.794,13.959,11.562,697.73,133.52,OH
36,19.9,6.368,5.771,18.308,18.706,881.51,178.86,OK
37,12.8,4.224,3.328,8.576,11.520,804.71,104.61,OR
38,18.2,9.100,5.642,17.472,16.016,905.99,153.86,PA
39,11.1,3.774,4.218,10.212,8.769,1148.99,148.58,RI
40,23.9,9.082,9.799,22.944,19.359,858.97,116.29,SC
41,19.4,6.014,6.402,19.012,16.684,669.31,96.87,SD
42,19.5,4.095,5.655,15.990,15.795,767.91,155.57,TN
43,19.4,7.760,7.372,17.654,16.878,1004.75,156.83,TX
44,11.3,4.859,1.808,9.944,10.848,809.38,109.48,UT
45,13.6,4.080,4.080,13.056,12.920,716.20,109.61,VT
46,12.7,2.413,3.429,11.049,11.176,768.95,153.72,VA
47,10.6,4.452,3.498,8.692,9.116,890.03,111.62,WA
48,23.8,8.092,6.664,23.086,20.706,992.61,152.56,WV
49,13.8,4.968,4.554,5.382,11.592,670.31,106.62,WI
50,17.4,7.308,5.568,14.094,15.660,791.14,122.04,WY

In [31]:
df.head()

,total,speeding,alcohol,not_distracted,no_previous,ins_premium,ins_losses,abbrev
0,18.8,7.332,5.640,18.048,15.040,784.55,145.08,AL
1,18.1,7.421,4.525,16.290,17.014,1053.48,133.93,AK
2,18.6,6.510,5.208,15.624,17.856,899.47,110.35,AZ
3,22.4,4.032,5.824,21.056,21.280,827.34,142.39,AR
4,12.0,4.200,3.360,10.920,10.680,878.41,165.63,CA

In [32]:
df.column

AttributeError: 'DataFrame' object has no attribute 'column'

In [33]:
df.column()

AttributeError: 'DataFrame' object has no attribute 'column'

In [35]:
list(df)[0]

'total'

In [50]:
for i in range(0,len(list(df))):
    transformed_header = list(df)[i].capitalize().replace('_',' ')
    
    df.rename(columns={list(df)[i]:transformed_header}, inplace = True)

In [51]:
df

,Total,Speeding,Alcohol,Not distracted,No previous,Ins premium,Ins losses,Abbrev
0,18.8,7.332,5.640,18.048,15.040,784.55,145.08,AL
1,18.1,7.421,4.525,16.290,17.014,1053.48,133.93,AK
2,18.6,6.510,5.208,15.624,17.856,899.47,110.35,AZ
3,22.4,4.032,5.824,21.056,21.280,827.34,142.39,AR
4,12.0,4.200,3.360,10.920,10.680,878.41,165.63,CA
5,13.6,5.032,3.808,10.744,12.920,835.50,139.91,CO
6,10.8,4.968,3.888,9.396,8.856,1068.73,167.02,CT
7,16.2,6.156,4.860,14.094,16.038,1137.87,151.48,DE
8,5.9,2.006,1.593,5.900,5.900,1273.89,136.05,DC
9,17.9,3.759,5.191,16.468,16.826,1160.13,144.18,FL
10,15.6,2.964,3.900,14.820,14.508,913.15,142.80,GA
11,17.5,9.450,7.175,14.350,15.225,861.18,120.92,HI
12,15.3,5.508,4.437,13.005,14.994,641.96,82.75,ID
13,12.8,4.608,4.352,12.032,12.288,803.11,139.15,IL
14,14.5,3.625,4.205,13.775,13.775,710.46,108.92,IN
15,15.7,2.669,3.925,15.229,13.659,649.06,114.47,IA
16,17.8,4.806,4.272,13.706,15.130,780.45,133.80,KS
17,21.4,4.066,4.922,16.692,16.264,872.51,137.13,KY
18,20.5,7.175,6.765,14.965,20.090,1281.55,194.78,LA
19,15.1,5.738,4.530,13.137,12.684,661.88,96.57,ME
20,12.5,4.250,4.000,8.875,12.375,1048.78,192.70,MD
21,8.2,1.886,2.870,7.134,6.560,1011.14,135.63,MA
22,14.1,3.384,3.948,13.395,10.857,1110.61,152.26,MI
23,9.6,2.208,2.784,8.448,8.448,777.18,133.35,MN
24,17.6,2.640,5.456,1.760,17.600,896.07,155.77,MS
25,16.1,6.923,5.474,14.812,13.524,790.32,144.45,MO
26,21.4,8.346,9.416,17.976,18.190,816.21,85.15,MT
27,14.9,1.937,5.215,13.857,13.410,732.28,114.82,NE
28,14.7,5.439,4.704,13.965,14.553,1029.87,138.71,NV
29,11.6,4.060,3.480,10.092,9.628,746.54,120.21,NH
30,11.2,1.792,3.136,9.632,8.736,1301.52,159.85,NJ
31,18.4,3.496,4.968,12.328,18.032,869.85,120.75,NM
32,12.3,3.936,3.567,10.824,9.840,1234.31,150.01,NY
33,16.8,6.552,5.208,15.792,13.608,708.24,127.82,NC
34,23.9,5.497,10.038,23.661,20.554,688.75,109.72,ND
35,14.1,3.948,4.794,13.959,11.562,697.73,133.52,OH
36,19.9,6.368,5.771,18.308,18.706,881.51,178.86,OK
37,12.8,4.224,3.328,8.576,11.520,804.71,104.61,OR
38,18.2,9.100,5.642,17.472,16.016,905.99,153.86,PA
39,11.1,3.774,4.218,10.212,8.769,1148.99,148.58,RI
40,23.9,9.082,9.799,22.944,19.359,858.97,116.29,SC
41,19.4,6.014,6.402,19.012,16.684,669.31,96.87,SD
42,19.5,4.095,5.655,15.990,15.795,767.91,155.57,TN
43,19.4,7.760,7.372,17.654,16.878,1004.75,156.83,TX
44,11.3,4.859,1.808,9.944,10.848,809.38,109.48,UT
45,13.6,4.080,4.080,13.056,12.920,716.20,109.61,VT
46,12.7,2.413,3.429,11.049,11.176,768.95,153.72,VA
47,10.6,4.452,3.498,8.692,9.116,890.03,111.62,WA
48,23.8,8.092,6.664,23.086,20.706,992.61,152.56,WV
49,13.8,4.968,4.554,5.382,11.592,670.31,106.62,WI
50,17.4,7.308,5.568,14.094,15.660,791.14,122.04,WY

In [52]:
df.round(2)

,Total,Speeding,Alcohol,Not distracted,No previous,Ins premium,Ins losses,Abbrev
0,18.8,7.33,5.64,18.05,15.04,784.55,145.08,AL
1,18.1,7.42,4.53,16.29,17.01,1053.48,133.93,AK
2,18.6,6.51,5.21,15.62,17.86,899.47,110.35,AZ
3,22.4,4.03,5.82,21.06,21.28,827.34,142.39,AR
4,12.0,4.20,3.36,10.92,10.68,878.41,165.63,CA
5,13.6,5.03,3.81,10.74,12.92,835.50,139.91,CO
6,10.8,4.97,3.89,9.40,8.86,1068.73,167.02,CT
7,16.2,6.16,4.86,14.09,16.04,1137.87,151.48,DE
8,5.9,2.01,1.59,5.90,5.90,1273.89,136.05,DC
9,17.9,3.76,5.19,16.47,16.83,1160.13,144.18,FL
10,15.6,2.96,3.90,14.82,14.51,913.15,142.80,GA
11,17.5,9.45,7.18,14.35,15.22,861.18,120.92,HI
12,15.3,5.51,4.44,13.00,14.99,641.96,82.75,ID
13,12.8,4.61,4.35,12.03,12.29,803.11,139.15,IL
14,14.5,3.62,4.20,13.78,13.78,710.46,108.92,IN
15,15.7,2.67,3.92,15.23,13.66,649.06,114.47,IA
16,17.8,4.81,4.27,13.71,15.13,780.45,133.80,KS
17,21.4,4.07,4.92,16.69,16.26,872.51,137.13,KY
18,20.5,7.18,6.76,14.96,20.09,1281.55,194.78,LA
19,15.1,5.74,4.53,13.14,12.68,661.88,96.57,ME
20,12.5,4.25,4.00,8.88,12.38,1048.78,192.70,MD
21,8.2,1.89,2.87,7.13,6.56,1011.14,135.63,MA
22,14.1,3.38,3.95,13.40,10.86,1110.61,152.26,MI
23,9.6,2.21,2.78,8.45,8.45,777.18,133.35,MN
24,17.6,2.64,5.46,1.76,17.60,896.07,155.77,MS
25,16.1,6.92,5.47,14.81,13.52,790.32,144.45,MO
26,21.4,8.35,9.42,17.98,18.19,816.21,85.15,MT
27,14.9,1.94,5.22,13.86,13.41,732.28,114.82,NE
28,14.7,5.44,4.70,13.96,14.55,1029.87,138.71,NV
29,11.6,4.06,3.48,10.09,9.63,746.54,120.21,NH
30,11.2,1.79,3.14,9.63,8.74,1301.52,159.85,NJ
31,18.4,3.50,4.97,12.33,18.03,869.85,120.75,NM
32,12.3,3.94,3.57,10.82,9.84,1234.31,150.01,NY
33,16.8,6.55,5.21,15.79,13.61,708.24,127.82,NC
34,23.9,5.50,10.04,23.66,20.55,688.75,109.72,ND
35,14.1,3.95,4.79,13.96,11.56,697.73,133.52,OH
36,19.9,6.37,5.77,18.31,18.71,881.51,178.86,OK
37,12.8,4.22,3.33,8.58,11.52,804.71,104.61,OR
38,18.2,9.10,5.64,17.47,16.02,905.99,153.86,PA
39,11.1,3.77,4.22,10.21,8.77,1148.99,148.58,RI
40,23.9,9.08,9.80,22.94,19.36,858.97,116.29,SC
41,19.4,6.01,6.40,19.01,16.68,669.31,96.87,SD
42,19.5,4.10,5.66,15.99,15.80,767.91,155.57,TN
43,19.4,7.76,7.37,17.65,16.88,1004.75,156.83,TX
44,11.3,4.86,1.81,9.94,10.85,809.38,109.48,UT
45,13.6,4.08,4.08,13.06,12.92,716.20,109.61,VT
46,12.7,2.41,3.43,11.05,11.18,768.95,153.72,VA
47,10.6,4.45,3.50,8.69,9.12,890.03,111.62,WA
48,23.8,8.09,6.66,23.09,20.71,992.61,152.56,WV
49,13.8,4.97,4.55,5.38,11.59,670.31,106.62,WI
50,17.4,7.31,5.57,14.09,15.66,791.14,122.04,WY

In [65]:
df = df.round(2)

In [66]:
df

,Total,Speeding,Alcohol,Not distracted,No previous,Ins premium,Ins losses,Abbrev
0,18.8,7.33,5.64,18.05,15.04,784.55,145.08,AL
1,18.1,7.42,4.53,16.29,17.01,1053.48,133.93,AK
2,18.6,6.51,5.21,15.62,17.86,899.47,110.35,AZ
3,22.4,4.03,5.82,21.06,21.28,827.34,142.39,AR
4,12.0,4.20,3.36,10.92,10.68,878.41,165.63,CA
5,13.6,5.03,3.81,10.74,12.92,835.50,139.91,CO
6,10.8,4.97,3.89,9.40,8.86,1068.73,167.02,CT
7,16.2,6.16,4.86,14.09,16.04,1137.87,151.48,DE
8,5.9,2.01,1.59,5.90,5.90,1273.89,136.05,DC
9,17.9,3.76,5.19,16.47,16.83,1160.13,144.18,FL
10,15.6,2.96,3.90,14.82,14.51,913.15,142.80,GA
11,17.5,9.45,7.18,14.35,15.22,861.18,120.92,HI
12,15.3,5.51,4.44,13.00,14.99,641.96,82.75,ID
13,12.8,4.61,4.35,12.03,12.29,803.11,139.15,IL
14,14.5,3.62,4.20,13.78,13.78,710.46,108.92,IN
15,15.7,2.67,3.92,15.23,13.66,649.06,114.47,IA
16,17.8,4.81,4.27,13.71,15.13,780.45,133.80,KS
17,21.4,4.07,4.92,16.69,16.26,872.51,137.13,KY
18,20.5,7.18,6.76,14.96,20.09,1281.55,194.78,LA
19,15.1,5.74,4.53,13.14,12.68,661.88,96.57,ME
20,12.5,4.25,4.00,8.88,12.38,1048.78,192.70,MD
21,8.2,1.89,2.87,7.13,6.56,1011.14,135.63,MA
22,14.1,3.38,3.95,13.40,10.86,1110.61,152.26,MI
23,9.6,2.21,2.78,8.45,8.45,777.18,133.35,MN
24,17.6,2.64,5.46,1.76,17.60,896.07,155.77,MS
25,16.1,6.92,5.47,14.81,13.52,790.32,144.45,MO
26,21.4,8.35,9.42,17.98,18.19,816.21,85.15,MT
27,14.9,1.94,5.22,13.86,13.41,732.28,114.82,NE
28,14.7,5.44,4.70,13.96,14.55,1029.87,138.71,NV
29,11.6,4.06,3.48,10.09,9.63,746.54,120.21,NH
30,11.2,1.79,3.14,9.63,8.74,1301.52,159.85,NJ
31,18.4,3.50,4.97,12.33,18.03,869.85,120.75,NM
32,12.3,3.94,3.57,10.82,9.84,1234.31,150.01,NY
33,16.8,6.55,5.21,15.79,13.61,708.24,127.82,NC
34,23.9,5.50,10.04,23.66,20.55,688.75,109.72,ND
35,14.1,3.95,4.79,13.96,11.56,697.73,133.52,OH
36,19.9,6.37,5.77,18.31,18.71,881.51,178.86,OK
37,12.8,4.22,3.33,8.58,11.52,804.71,104.61,OR
38,18.2,9.10,5.64,17.47,16.02,905.99,153.86,PA
39,11.1,3.77,4.22,10.21,8.77,1148.99,148.58,RI
40,23.9,9.08,9.80,22.94,19.36,858.97,116.29,SC
41,19.4,6.01,6.40,19.01,16.68,669.31,96.87,SD
42,19.5,4.10,5.66,15.99,15.80,767.91,155.57,TN
43,19.4,7.76,7.37,17.65,16.88,1004.75,156.83,TX
44,11.3,4.86,1.81,9.94,10.85,809.38,109.48,UT
45,13.6,4.08,4.08,13.06,12.92,716.20,109.61,VT
46,12.7,2.41,3.43,11.05,11.18,768.95,153.72,VA
47,10.6,4.45,3.50,8.69,9.12,890.03,111.62,WA
48,23.8,8.09,6.66,23.09,20.71,992.61,152.56,WV
49,13.8,4.97,4.55,5.38,11.59,670.31,106.62,WI
50,17.4,7.31,5.57,14.09,15.66,791.14,122.04,WY

In [67]:
df.to_sql('Car_crash',con=engine,index=False,if_exists='append')

In [72]:
dt = df
for x in dt.index:
    if(dt.loc[x,'Speeding']< 4 or dt.loc[x,'Alcohol'] < 4):
        dt.drop(x,inplace=True)

In [73]:
dt

,Total,Speeding,Alcohol,Not distracted,No previous,Ins premium,Ins losses,Abbrev
0,18.8,7.33,5.64,18.05,15.04,784.55,145.08,AL
2,18.6,6.51,5.21,15.62,17.86,899.47,110.35,AZ
11,17.5,9.45,7.18,14.35,15.22,861.18,120.92,HI
18,20.5,7.18,6.76,14.96,20.09,1281.55,194.78,LA
25,16.1,6.92,5.47,14.81,13.52,790.32,144.45,MO
26,21.4,8.35,9.42,17.98,18.19,816.21,85.15,MT
33,16.8,6.55,5.21,15.79,13.61,708.24,127.82,NC
34,23.9,5.50,10.04,23.66,20.55,688.75,109.72,ND
36,19.9,6.37,5.77,18.31,18.71,881.51,178.86,OK
38,18.2,9.10,5.64,17.47,16.02,905.99,153.86,PA
40,23.9,9.08,9.80,22.94,19.36,858.97,116.29,SC
41,19.4,6.01,6.40,19.01,16.68,669.31,96.87,SD
43,19.4,7.76,7.37,17.65,16.88,1004.75,156.83,TX
48,23.8,8.09,6.66,23.09,20.71,992.61,152.56,WV
50,17.4,7.31,5.57,14.09,15.66,791.14,122.04,WY

In [75]:
dt.to_sql('Car_crash',con=engine,index=False,if_exists='append')